server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8$serverTimezone=Asia/Shanghai
    username: root
    password: root
   redis:
     host: localhost #Redis服务地址
     datebase: 0 #Redis数据库索引（默认为0）
     port: 6379 #Redis服务器连接端口
     password: #Redis服务连接密码（默认为空）
     jedis:
       pool:
         max-active: 8 #连接池最大连接数（使用负值表示没有限制）
         max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 8 #连接池中的最大空闲连接
         min-idle: 0 #连接池中的最小空闲连接
       timeout: 3000ms #连接超时时间:
    data:
      elasticsearch:
        repositories:
          enable: true
        cluster-nodes: 127.0.0.1:9300 #es的连接地址及端口号
        cluster-name: elasticsearch #es 集群的名称
    mongodb:
      host: localhost #mongodb的连接地址
      port: 27017 #mongo连接端口号
      database: mall-port #mongo的连接的连接库
    rabbitmq:
      host: localhost
      port: 5672
      virtual-host: /mall #rabbitmq的虚拟host
      username: mail
      password: mail
      publisher-confirms: true #如果对异步消息需要回调必须设置为true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
mybatis:
  mapper-locations:
    -classpath:mapper/*.xml
    -classpath*:com/**/mapper/*.xml

#自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 #验证码超时时间

#自定义jwt key:
      tokenHeader: Authorization #JWT存储的请求头
      secret: mySecret #JWT加解密使用的秘钥
      expiration: 604800 #JWT的超期限时间（60*60*24）
      tokenHead: Bearer #JWT负载中拿到开头

#OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com #oss对外服务的访问域名
    accessKeyId: test #访问身份验证中用到用户标识
    accessKeySecret: test #用户用于加密签名字符串和oss用来验证签名字符串的秘钥
    bucketName: fh-oss #oss的存储空间
    policy:
      expire: 300 #签名有效期（S）
    maxSize: 10 #上传文件大小 （M）
    callback: http://localhost:8080/aliyun/oss/callback #文件上传成功后的回调地址
    dir:
      prefix: mall/images/ #上传文件夹路径前缀
